name: Generate and Publish Dokka Docs

on:
  push:
    tags:
      - 'v*.*.*'  # Runs on version tags (e.g., v1.0.0)
  workflow_dispatch:

jobs:
  generate-html-doc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Generate documentation
        uses: ./.github/actions/documentation
        with:
          token: '${{ secrets.GH_PAT }}'